// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System_Uznawania_Przychodów.Data;

#nullable disable

namespace System_Uznawania_Przychodów.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Addr1",
                            Email = "client1@test.com",
                            Phone = "100000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Addr2",
                            Email = "client2@test.com",
                            Phone = "100000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Addr3",
                            Email = "client3@test.com",
                            Phone = "100000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Addr4",
                            Email = "client4@test.com",
                            Phone = "100000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Addr5",
                            Email = "client5@test.com",
                            Phone = "100000005"
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.CompanyClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClientId");

                    b.HasIndex("Krs")
                        .IsUnique();

                    b.ToTable("CompanyClients");

                    b.HasData(
                        new
                        {
                            ClientId = 4,
                            CompanyName = "Corp1",
                            Krs = "0000000001"
                        },
                        new
                        {
                            ClientId = 5,
                            CompanyName = "Corp2",
                            Krs = "0000000002"
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdditionalSupportYears")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("SignedAt")
                        .HasColumnType("date");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Contracts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalSupportYears = 0,
                            ClientId = 1,
                            EndDate = new DateOnly(2026, 1, 15),
                            IsActive = true,
                            Price = 10000m,
                            SignedAt = new DateOnly(2026, 1, 10),
                            SoftwareId = 1,
                            SoftwareVersion = "3.2.1",
                            StartDate = new DateOnly(2026, 1, 1),
                            TotalPaid = 10000m
                        },
                        new
                        {
                            Id = 2,
                            AdditionalSupportYears = 1,
                            ClientId = 2,
                            EndDate = new DateOnly(2026, 6, 20),
                            IsActive = true,
                            Price = 5000m,
                            SoftwareId = 2,
                            SoftwareVersion = "1.8.0",
                            StartDate = new DateOnly(2026, 6, 1),
                            TotalPaid = 2000m
                        },
                        new
                        {
                            Id = 3,
                            AdditionalSupportYears = 0,
                            ClientId = 3,
                            EndDate = new DateOnly(2026, 5, 20),
                            IsActive = false,
                            Price = 8000m,
                            SoftwareId = 3,
                            SoftwareVersion = "2.0.4",
                            StartDate = new DateOnly(2026, 5, 1),
                            TotalPaid = 0m
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.ContractPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractPayments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10000m,
                            ContractId = 1,
                            PaidAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000m,
                            ContractId = 2,
                            PaidAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOnAllProducts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PurchaseModel")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOnAllProducts = true,
                            Name = "Disc1",
                            Percentage = 10m,
                            PurchaseModel = 0,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOnAllProducts = true,
                            Name = "Disc2",
                            Percentage = 15m,
                            PurchaseModel = 1,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOnAllProducts = false,
                            Name = "Disc3",
                            Percentage = 8m,
                            PurchaseModel = 0,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOnAllProducts = true,
                            Name = "Disc4",
                            Percentage = 20m,
                            PurchaseModel = 0,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.IndividualClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ClientId");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("IndividualClients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            FirstName = "First1",
                            LastName = "Last1",
                            Pesel = "00000000001"
                        },
                        new
                        {
                            ClientId = 2,
                            FirstName = "First2",
                            LastName = "Last2",
                            Pesel = "00000000002"
                        },
                        new
                        {
                            ClientId = 3,
                            FirstName = "First3",
                            LastName = "Last3",
                            Pesel = "00000000003"
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MonthlySubscriptionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("YearlyLicensePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Softwares", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Finance",
                            CurrentVersion = "3.2.1",
                            Description = "Desc1",
                            MonthlySubscriptionPrice = 1000m,
                            Name = "Prog1",
                            YearlyLicensePrice = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Education",
                            CurrentVersion = "1.8.0",
                            Description = "Desc2",
                            MonthlySubscriptionPrice = 500m,
                            Name = "Prog2",
                            YearlyLicensePrice = 5000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Education",
                            CurrentVersion = "2.0.4",
                            Description = "Desc3",
                            MonthlySubscriptionPrice = 800m,
                            Name = "Prog3",
                            YearlyLicensePrice = 8000m
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.SoftwareDiscount", b =>
                {
                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("SoftwareDiscounts", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            DiscountId = 3
                        },
                        new
                        {
                            SoftwareId = 2,
                            DiscountId = 3
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.SoftwareVersion", b =>
                {
                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoftwareId", "Version");

                    b.ToTable("SoftwareVersions", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            Version = "1.0.0"
                        },
                        new
                        {
                            SoftwareId = 1,
                            Version = "2.0.0"
                        },
                        new
                        {
                            SoftwareId = 1,
                            Version = "3.2.1"
                        },
                        new
                        {
                            SoftwareId = 2,
                            Version = "1.0.0"
                        },
                        new
                        {
                            SoftwareId = 2,
                            Version = "1.8.0"
                        },
                        new
                        {
                            SoftwareId = 3,
                            Version = "1.0.0"
                        },
                        new
                        {
                            SoftwareId = 3,
                            Version = "2.0.4"
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("NextPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("RenewalPeriodMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("RenewalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Subscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 4,
                            HasPaid = true,
                            IsCancelled = false,
                            Name = "Sub1",
                            NextPeriodStart = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenewalPeriodMonths = 1,
                            RenewalPrice = 1000m,
                            SoftwareId = 1,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 5,
                            HasPaid = true,
                            IsCancelled = false,
                            Name = "Sub2",
                            NextPeriodStart = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenewalPeriodMonths = 12,
                            RenewalPrice = 5000m,
                            SoftwareId = 2,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            HasPaid = false,
                            IsCancelled = true,
                            Name = "Sub3",
                            NextPeriodStart = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RenewalPeriodMonths = 1,
                            RenewalPrice = 800m,
                            SoftwareId = 3,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPayments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000m,
                            PaidAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000m,
                            PaidAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5000m,
                            PaidAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 800m,
                            PaidAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 3
                        });
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.CompanyClient", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Client", "Client")
                        .WithOne("CompanyClient")
                        .HasForeignKey("System_Uznawania_Przychodów.Domain.Entities.CompanyClient", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Contract", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Software", "Software")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.ContractPayment", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.IndividualClient", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Client", "Client")
                        .WithOne("IndividualClient")
                        .HasForeignKey("System_Uznawania_Przychodów.Domain.Entities.IndividualClient", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.SoftwareDiscount", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Discount", "Discount")
                        .WithMany("SoftwareDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Software", "Software")
                        .WithMany("SoftwareDiscounts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.SoftwareVersion", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Software", "Software")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Software", "Software")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("System_Uznawania_Przychodów.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Client", b =>
                {
                    b.Navigation("CompanyClient");

                    b.Navigation("Contracts");

                    b.Navigation("IndividualClient");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Discount", b =>
                {
                    b.Navigation("SoftwareDiscounts");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Software", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("SoftwareDiscounts");

                    b.Navigation("Subscriptions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("System_Uznawania_Przychodów.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
