<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>System_Uznawania_Przychodów</RootNamespace>
        <UserSecretsId>a15ca8db-c362-46d0-bdbb-12999967e360</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.1" />
    </ItemGroup>

</Project>
