<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>e98c66c9-af4f-44ab-8e33-5d2f9b3876d5</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6"/>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7"/>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="NewDirectory1\GET.json" />
      <_ContentIncludedByDefault Remove="NewDirectory1\POST.json" />
    </ItemGroup>

</Project>
